### ISSUE TITLE
7-day-incidence values are not correct

### ISSUE THREAD

**Issue by 16flotho** [ivansieder/corona-bz-api#2]
All values, which calculate the 7-day-incidence are different from the official website of south tyrol.

The reason, why its different, is because you take **533439** as number of inhabitants. The official website instead takes **535354** as number of inhabitants, as stated there (http://www.provinz.bz.it/sicherheit-zivilschutz/zivilschutz/aktuelle-daten-zum-coronavirus.asp)

I checked this on the value `sevenDaysIncidencePerOneHundredThousandTotalPositiveTested`, but I think this problem affects every 7-day-incidence value.

**Comment by ivansieder** [comment]
Has been updated now and should be live inside the API, thank you! https://github.com/ivansieder/corona-bz-api/blob/master/index.js#L169
