### ISSUE TITLE
Api currently not working?

### ISSUE THREAD

**Issue by 16flotho** [ivansieder/corona-bz-api#4]
Hello,

my bot, which uses your API doesn't receive any updates for two days. Also, the data, which was fetched before, was partly incorrect. I noticed it because the seven-day incidences since 30.03.2022 were negative. As I opened the API myself I saw that the data ends at the date "2022-03-29".

Clearly there must be something wrong with the API. A wild guess would be that there is a problem caused by the [fixed discrepancy between national and regional infections](https://www.sabes.it/de/news.asp?aktuelles_action=4&aktuelles_article_id=665041#:~:text=Zahlen%20zu%20den%20Neuinfektionen%20in%20Einklang%20gebracht).

Thank you for looking into it :).

**Comment by ivansieder** [comment]
@16flotho I'm afraid to tell you that due to too many changes on the side of the SABES and the lack of time on my side to adapt the scripts from day to day, I had to disable the whole API :(

**Comment by 16flotho** [comment]
That is unfortunate to hear that...

Thanks anyway for the great API. It was really helpful :).

**Comment by 16flotho** [comment]
For anyone interested in an API for COVID-19 Data of South Tyrol: I've created a similar project, which parses data from the official website and provides the data as API.

https://github.com/16flotho/corona-bz-parser
